// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHTeF_ixPF3Zca9Bibl9k9mPCMHTPnCeQ',
    appId: '1:913603683509:web:8b9955fda67f5f7d808afc',
    messagingSenderId: '913603683509',
    projectId: 'app-project-e5b9a',
    authDomain: 'app-project-e5b9a.firebaseapp.com',
    storageBucket: 'app-project-e5b9a.firebasestorage.app',
    measurementId: 'G-H07WRSD2TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfVINpu8_moC6ohlB3UgLZGq1ryAglohA',
    appId: '1:913603683509:android:b18bd7c0032f2054808afc',
    messagingSenderId: '913603683509',
    projectId: 'app-project-e5b9a',
    storageBucket: 'app-project-e5b9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVsNNGe9wARonwS5bbaBfzgle3aAC7cUY',
    appId: '1:913603683509:ios:7377b77fab5af1d4808afc',
    messagingSenderId: '913603683509',
    projectId: 'app-project-e5b9a',
    storageBucket: 'app-project-e5b9a.firebasestorage.app',
    androidClientId: '913603683509-uu30n0g3upr4kcdhm15hau1sdk3t1na6.apps.googleusercontent.com',
    iosClientId: '913603683509-ta76obf8fldq689b889vfrqkputbq3kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.linku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVsNNGe9wARonwS5bbaBfzgle3aAC7cUY',
    appId: '1:913603683509:ios:7377b77fab5af1d4808afc',
    messagingSenderId: '913603683509',
    projectId: 'app-project-e5b9a',
    storageBucket: 'app-project-e5b9a.firebasestorage.app',
    androidClientId: '913603683509-uu30n0g3upr4kcdhm15hau1sdk3t1na6.apps.googleusercontent.com',
    iosClientId: '913603683509-ta76obf8fldq689b889vfrqkputbq3kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.linku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHTeF_ixPF3Zca9Bibl9k9mPCMHTPnCeQ',
    appId: '1:913603683509:web:12c38d7e8ac49c18808afc',
    messagingSenderId: '913603683509',
    projectId: 'app-project-e5b9a',
    authDomain: 'app-project-e5b9a.firebaseapp.com',
    storageBucket: 'app-project-e5b9a.firebasestorage.app',
    measurementId: 'G-08RVLJ4TLZ',
  );
}
